INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('The Raptor Rescue Society', 'A non-profit wildlife rehabilitation centre located in the Cowichan Valley, dedicated to rescuing, rehabilitating and releasing wild raptors and other birds from all over lower Vancouver Island', 'Susana48@hotmail.com', '233-644-5245', 'Cowichan Valley', 'https://www.raptorrescuesociety.com/wp-content/uploads/2020/10/56603194_844623842545139_2389146777547702272_n-1024x768.jpg', 'https://www.raptorrescuesociety.com', '{ "question1": "Do you own or have access to a vehicle, and a valid Drivers license?", "question2":"Are you willing to provide a criminal record check?", "question3":"Are you comfortable handling wild animals?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('Chemainus Theatre Festival', 'We are a vibrant, established and fully professional theatre nestled in the seaside community of Chemainus, BC. As a non-profit society, we exist to serve Vancouver Island and its visitors by creating exceptional theatre.', 'Susana48@hotmail.com', '233-644-5245', 'Chemainus', 'https://3a0nh63bi31e2mggl320lr33-wpengine.netdna-ssl.com/wp-content/uploads/2021/03/24389962_web1_210304-CHC-Chemainus-Theatre-update-funds_3.jpg', 'https://chemainustheatrefestival.ca/', '{"question1": "Do you like hats?", "question2": "Are you open to reconsidering that position?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('A real volunteer place', 'Come volunteer for us, a real human. You will definitely survive', 'Harry_Price@hotmail.com', '(496) 827-9672 x041', 'Willland', 'http://placeimg.com/640/480', 'https://river.com', '{"question1": "Do you like hats?", "question2": "Are you open to reconsidering that position?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('Doctor Daves Book Emporium', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', 'Susana48@hotmail.com', '233-644-5245', 'Fadelshire', 'http://placeimg.com/640/480', 'https://ezequiel.com', '{"question1": "Do you like hats?", "question2": "Are you open to reconsidering that position?"}');


