INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('The Raptor Rescue Society', 'A non-profit wildlife rehabilitation centre located in the Cowichan Valley, dedicated to rescuing, rehabilitating and releasing wild raptors and other birds from all over lower Vancouver Island', 'info@raptorrescuesociety.com', '233-644-5245', 'Cowichan Valley', 'https://pnwraptors.com/wp-content/uploads/2016/11/bald-eagle.jpg', 'https://www.raptorrescuesociety.com', '{ "question1": "Do you have a vehicle or a valid Drivers license?", "question2":"Are you willing to provide a criminal record check?", "question3":"Are you comfortable handling wild animals?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('Chemainus Theatre Festival', 'We are a vibrant, established and fully professional theatre nestled in the seaside community of Chemainus, BC. As a non-profit society, we exist to serve Vancouver Island and its visitors by creating exceptional theatre.', 'Susana48@hotmail.com', '233-644-5245', 'Chemainus', 'https://3a0nh63bi31e2mggl320lr33-wpengine.netdna-ssl.com/wp-content/uploads/2021/03/24389962_web1_210304-CHC-Chemainus-Theatre-update-funds_3.jpg', 'https://chemainustheatrefestival.ca/', '{"question1": "Do you like hats?", "question2": "Are you open to reconsidering that position?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('A real volunteer place', 'Come volunteer for us, a real human. You will definitely survive', 'Harry_Price@hotmail.com', '(496) 827-9672 x041', 'Willland', 'https://blog.vitalchek.com/wp-content/uploads/2016/11/National-Human-Rights-Month-1.jpg', 'https://river.com', '{"question1": "Do you like hats?", "question2": "Are you open to reconsidering that position?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('Doctor Daves Book Emporium', 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', 'Susana48@hotmail.com', '233-644-5245', 'Fadelshire', 'https://content.fortune.com/wp-content/uploads/2015/11/screen-shot-2015-11-03-at-7-04-13-am.png?resize=750,500', 'https://ezequiel.com', '{"question1": "Do you like hats?", "question2": "Are you open to reconsidering that position?"}');

INSERT INTO organizations (name, description, primary_email, primary_phone, location, image_url, website, application_config) VALUES ('Pacific Cinematheque', 'The Cinematheque is a film institute and media education centre devoted to understanding the art and history of Canadian and international cinema and the impact in our lives.', 'theatre@​theCinematheque.​ca', '604 688 8202', 'Vancouver', 'https://thecinematheque.ca/assets/images/films/_small169/Cinematheque1.jpg', 'https://thecinematheque.ca/', '{"question1": "Do you like films?", "question2": "Open to reconsidering that position?", "question3":"Can you provide a criminal record check?", "question4": "Do you have vehicle or a valid Drivers license?"}');



