INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Clean theater', 'Vacuum theater floor and check seats for garbage', '2021-03-29', '2021-03-31', 5, 'https://i.pinimg.com/originals/e8/19/2d/e8192df7e0111f6ac40b9f186aa2084a.jpg', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Feed baby eagles', 'Feed baby eagles 2-8x a day', '2021-04-01', '2021-04-20', 3, 'https://s3.us-east-2.amazonaws.com/journeynorth.org/images/graphics/eagle/chicks_dave_menke.jpg', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Care and Health of Owls', 'Feed owls medicine 1-4x a day', '2021-04-02', '2021-04-20', 10, 'https://unsplash.com/photos/KltoLK6Mk-g', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Clean and maintain habitats', 'clean and maintain habitats 2x a day. Use proper cleaning supplies in dedicated locations', '2021-03-27', '2021-03-28', 4, 'https://unsplash.com/photos/BUXdQh53eis', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Retock Food', 'Make sure all food is restocked. check at the end of day. This is a daily task', '2021-03-27', '2021-03-28', 1, 'https://unsplash.com/photos/cckf4TsHAuw', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Stock Popcorn', 'Restock Popcorn and popcorn bags', '2021-03-29', '2021-03-31', 2, 'https://unsplash.com/photos/q8P8YoR6erg', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Sales', 'Check Daily Sales', '2021-04-15', '2021-04-16', 2, 'https://unsplash.com/photos/nFLmPAf9dVc', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Print Will Call Tickets', 'Print Tickets', '2021-04-15', '2021-04-16', 1, 'https://unsplash.com/photos/gT-Sob4njj8', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Clean theater', 'Vacuum theater floor and check seats for garbage', '2021-03-29', '2021-03-31', 3, 'https://i.pinimg.com/originals/e8/19/2d/e8192df7e0111f6ac40b9f186aa2084a.jpg', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Delievery of Newsletters', 'Drop off  newsletters to various locations in the city', '2021-03-29', '2021-03-31', 20, 'https://unsplash.com/photos/SOVuvSqyHNY', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Sales', 'Check Daily Sales', '2021-03-28', '2021-03-29', 2, 'https://unsplash.com/photos/nFLmPAf9dVc', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Print Will Call Tickets', 'Print Tickets', '2021-03-28', '2021-03-29', 1, 'https://unsplash.com/photos/gT-Sob4njj8', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Give Time', 'Drop by and ask if there is something to do', '2021-04-15', '2021-04-16', 15, 'https://unsplash.com/photos/J-Jb1niw1j0', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Website For Tasks', 'Look to see if there are any tasks to volunteer for', '2021-04-15', '2021-04-16', 15, 'https://unsplash.com/photos/I_pOqP6kCOI', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Volunteer Applications', 'Check and verify Volunteers', '2021-04-15', '2021-04-16', 4, 'https://unsplash.com/photos/RLw-UC03Gwc', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Call In To Approve Volunteers', 'Call to inform volunteers they are approved', '2021-04-15', '2021-04-16', 3, 'https://unsplash.com/photos/315vPGsAFUk', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Stock Books', 'stock new and old books', '2021-04-15', '2021-04-16', 4, 'https://unsplash.com/photos/sfL_QOnmy00', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Data Entry', 'Enter books in the database', '2021-04-15', '2021-04-16', 1, 'https://unsplash.com/photos/Hcfwew744z4', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Dust', 'Dust the books', '2021-04-15', '2021-04-16', 1, 'https://unsplash.com/photos/XKeiyj85aJo', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Opening Store', 'Open Store Routine: Check Notes from Manager', '2021-04-15', '2021-04-16', 3, 'https://unsplash.com/photos/ONzByifWVJs', 4, 'Chemainus');



