INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Clean theater', 'Vacuum theater floor and check seats for garbage', '2021-03-29', '2021-03-31', 5, 'https://i.pinimg.com/originals/e8/19/2d/e8192df7e0111f6ac40b9f186aa2084a.jpg', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Feed baby eagles', 'Feed baby eagles 2-8x a day', '2021-04-01', '2021-04-20', 3, 'https://s3.us-east-2.amazonaws.com/journeynorth.org/images/graphics/eagle/chicks_dave_menke.jpg', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Care and Health of Owls', 'Feed owls medicine 1-4x a day', '2021-04-02', '2021-04-20', 10, 'https://cdn.download.ams.birds.cornell.edu/api/v1/asset/297363481/900', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Clean and maintain habitats', 'clean and maintain habitats 2x a day. Use proper cleaning supplies in dedicated locations', '2021-03-27', '2021-03-28', 4, 'https://assets.change.org/photos/0/ks/oe/LJksOeSuZDQfqCY-1600x900-noPad.jpg?1611744966', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Restock Food', 'Make sure all food is restocked. check at the end of day. This is a daily task', '2021-03-27', '2021-03-28', 1, 'https://i.cbc.ca/1.1573654.1551289489!/httpImage/image.jpg_gen/derivatives/16x9_780/hi-wdr-food-bank.jpg', 1, 'Fadelshire');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Stock Popcorn', 'Restock Popcorn and popcorn bags. Make sure that all th seasoning flavours are filled up in the proper jars.', '2021-03-29', '2021-03-31', 2, 'https://thecinematheque.ca/assets/files/general/_small169/Staff_Volunteer_Image2.jpg', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Sales', 'Check Daily Sales from the box office. Send numbers to the box office manager.', '2021-04-15', '2021-04-16', 2, 'https://thecinematheque.ca/assets/files/general/_small169/Staff_Volunteer_Image.jpg', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Print Will Call Tickets', 'Print Tickets from the box office. Make sure tickets are printed 1hr before show time.', '2021-04-15', '2021-04-16', 1, 'https://www.glossophilia.org/wp-content/uploads/Will-Call-1.jpg', 2, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Clean theater', 'Vacuum theater floor and check seats for garbage. Take garbage out to the dumpster.', '2021-03-29', '2021-03-31', 3, 'https://thecinematheque.ca/assets/images/films/_small169/About.jpg', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Delievery of Newsletters', 'Drop off  newsletters to various locations in the city. Make sure once done to check back in with volunteer manager.', '2021-03-29', '2021-03-31', 20, 'https://thecinematheque.ca/assets/files/general/_small169/Guide_2.jpg', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Sales', 'Check Daily Sales from the box office. Send numbers to the box office manager.', '2021-03-28', '2021-03-29', 2, 'https://thecinematheque.ca/assets/files/general/_small169/Staff_Volunteer_Image.jpg', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Print Will Call Tickets', 'Print Tickets from the box office. Make sure tickets are printed 1hr before show time.', '2021-03-28', '2021-03-29', 1, 'https://www.glossophilia.org/wp-content/uploads/Will-Call-1.jpg', 5, 'Vancouver');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Give Time', 'Drop by and ask if there is something to do. Check in with volunteer manager to recieve tasks.', '2021-04-15', '2021-04-16', 15, 'https://cdn.corporatefinanceinstitute.com/assets/volunteer-management-1200x800.jpeg', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Website For Tasks', 'Look to see if there are any tasks to volunteer for or if there are other organizations to work with.', '2021-04-15', '2021-04-16', 15, 'https://cdn.elearningindustry.com/wp-content/uploads/2019/09/online-courses-what-students-want.jpg', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Check Volunteer Applications', 'Check and verify Volunteers. Call references and make sure they pass criminal record checks.', '2021-04-15', '2021-04-16', 4, 'https://www.recruiter.com/i/wp-content/uploads/2016/08/magnifying.jpg', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Call In To Approve Volunteers', 'Call to inform volunteers they are approved for the tasks. Make sure they go through the online orientation via the email.', '2021-04-15', '2021-04-16', 3, 'https://www.incimages.com/uploaded_files/image/1920x1080/getty_517518545_338975.jpg', 3, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Stock Books', 'Stock new and old books. Make sure the display at the front of the store is created first. ', '2021-04-15', '2021-04-16', 4, 'https://thecinematheque.ca/assets/files/general/_small169/library2.jpg', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Data Entry', 'Enter books in the database, Make sure to check the database binder in order to confirm what the previous volunteer has done.', '2021-04-15', '2021-04-16', 1, 'https://www.invensis.net/blog/wp-content/uploads/2020/07/data-entry-automation-benefits.jpg', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Dust', 'Dust the books. Make sure that both floors of the stairs are covered.', '2021-04-15', '2021-04-16', 1, 'https://www.nedcc.org/assets/media/images/leaflets/7_2%20surface%20brushing_2.jpg', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Opening Store', 'Open Store Routine: Check Notes from Manager There are many tasks to do for the opening routine.', '2021-04-15', '2021-04-16', 3, 'https://s.hdnux.com/photos/01/11/65/03/19353849/3/1150x0.jpg', 4, 'Chemainus');
INSERT INTO tasks (name, description, start_date, end_date, spots, image_url, organization_id, location) VALUES ('Annual RRS Fundraiser', 'Need support for the event. Multiple jobs required for all parts of the day for this event. See volunteer manager for details', '2021-05-09', '2021-05-10', 25, 'https://thecinematheque.ca/assets/files/general/_small169/venue.jpg', 1, 'Fadelshire');



