INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (1, 1, 'true', '{"name":{"question":"name", "answer": "Larry Benjamins"}, "email":{"question":"email", "answer":"realemail@yahoo.gov"}, "phone":{"question":"phone", "answer":"555-655-1111"}, "question1":{"question": "Do you own or have access to a vehicle, and a valid Drivers license?", "answer":"Yes"}, "question2":{"question":"Are you willing to provide a criminal record check?", "answer":"Yes"}, "question3":{"question":"Are you comfortable handling wild animals?", "answer":"I am certainly willing to learn!"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (2, 2, 'pending', '{"name":{"question":"name", "answer": "Sam Bones"}, "email":{"question":"email", "answer":"Adonnis55gmail.com"}, "phone":{"question":"phone", "answer":"555-655-1111"}, "question1":{"question": "Do you own or have access to a vehicle, and a valid Drivers license?", "answer":"Yes"}, "question2":{"question":"Are you willing to provide a criminal record check?", "answer":"Yes"}, "question3":{"question":"Are you comfortable handling wild animals?", "answer":"I am certainly willing to learn!"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (5, 1, 'pending', '{"name":{"question":"name", "answer": "Berge Lovin"}, "email":{"question":"email", "answer":"Adonnis55gmail.com"}, "phone":{"question":"phone", "answer":"555-655-1111"}, "question1":{"question": "Do you own or have access to a vehicle, and a valid Drivers license?", "answer":"No"}, "question2":{"question":"Are you willing to provide a criminal record check?", "answer":"Nope"}, "question3":{"question":"Are you comfortable handling wild animals?", "answer":"Nothing scares me more than animals, especially wild ones"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (3, 1, 'pending', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (4, 2, 'false', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (4, 1, 'pending', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (6, 1, 'pending', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (1, 4, 'true', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (5, 3, 'true', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (4, 4, 'true', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');

INSERT INTO approved_users (user_id, organization_id, approved, application) VALUES (5, 5, 'true', '{"name":{"question":"name", "answer":"Laddy James"}, "email":{"question":"email", "answer":"banana@yahoo.gov"}, "phone":{"question":"phone", "answer":"111-111-1111"}, "question1":{"question": "Do you have an opinion on ferrets?", "answer":"Strongly held ones, yes"}}');
