INSERT INTO signups (approved_user_id, task_id) VALUES (2, 1);
INSERT INTO signups (approved_user_id, task_id) VALUES (3, 1);
INSERT INTO signups (approved_user_id, task_id) VALUES (5, 1);
INSERT INTO signups (approved_user_id, task_id) VALUES (1, 19);
INSERT INTO signups (approved_user_id, task_id) VALUES (2, 3);
INSERT INTO signups (approved_user_id, task_id) VALUES (4, 2);
INSERT INTO signups (approved_user_id, task_id) VALUES (1, 3);
INSERT into signups (approved_user_id, task_id) VALUES (2, 15);
INSERT into signups (approved_user_id, task_id) VALUES (1, 5);
