DROP TABLE IF EXISTS signups CASCADE;
CREATE TABLE signups (
  id SERIAL PRIMARY KEY NOT NULL,
  approved_user_id INTEGER REFERENCES approved_users(id) ON DELETE CASCADE,
  task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE
);
ALTER TABLE signups OWNER TO labber;